language = "C"

include_guard = "LLT_H"

style = "both"

[export]
include = [
  "ModuleHandle",
  "FuncHandle",
  "BlockHandle",
  "InstHandle",
  "GlobalVarHandle"
]

[parse]
parse_deps = true
clean = true